// Configuration file - This will be generated by Terraform
// Replace these values with your actual AWS resources
window.CONFIG = {
    // AWS Region
    region: 'us-east-1',
    
    // Cognito Configuration
    cognito: {
        userPoolId: 'REPLACE_WITH_USER_POOL_ID',
        userPoolWebClientId: 'REPLACE_WITH_CLIENT_ID',
        identityPoolId: 'REPLACE_WITH_IDENTITY_POOL_ID',
        domain: 'REPLACE_WITH_COGNITO_DOMAIN'
    },
    
    // Bedrock Configuration
    bedrock: {
        knowledgeBaseId: 'REPLACE_WITH_KNOWLEDGE_BASE_ID',
        modelId: 'us.anthropic.claude-sonnet-4-20250514-v1:0'
    },
    
    // MCP Server Configuration (optional)
    mcpServerUrl: '' // Leave empty if not using MCP server
};
